name: auto-clang-format
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: '.'
          exclude: './extern'
          extensions: 'cpp,hpp'
          clangFormatVersion: 12
          inplace: True
      - uses: EndBug/add-and-commit@v4
        with:
          author_name: Clang-Format Robot
          author_email: robot@example.com
          message: ':art: Committing clang-format changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}